name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: dotnet test
        run: dotnet test --configuration Release

      - name: dotnet publish
        run: dotnet publish src/GitHubActionsDotNet.Api --configuration Release -o artifacts

      - uses: actions/upload-artifact@v4
        with:
          name: api-artifact
          path: artifacts/

  deploy_dev:
    needs: build
    name: "Deploy to dev"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        name: Download artifact
        with:
          name: api-artifact
          path: artifacts-downloaded/

      - name: "Deploy to Azure App Service"
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-something-tgi-doesnot-exist # Replace with good name
          package: artifacts-downloaded/
