name: Secrets workflow

on:
  pull_request:
    branches: ["main"]

jobs:
  secrets:
    name: Secrets workflow
    runs-on: ubuntu-latest

    steps:
      - name: echo env
        run: echo "${{ secrets.SECRET_API_KEY }}"
